"""
Answer Service — main RAG Q&A service.
Query → Hybrid Retrieval → Reranking → Context → Gemini → Structured Response
"""
import logging
import re
from langchain_core.messages import HumanMessage

from ..rag.hybrid_search import get_hybrid_searcher
from ..rag.reranker import rerank
from ..rag.context_builder import build_context, documents_to_source_chunks
from ..services.llm import get_llm
from ..prompts.answer_prompt import answer_prompt
from ..prompts.code_prompt import code_prompt
from ..schemas.chat import ChatResponse, SourceChunk
from ..core.config import get_settings

logger = logging.getLogger(__name__)


def _detect_confidence(answer_text: str) -> str:
    """Heuristic confidence detection from LLM response."""
    lower = answer_text.lower()
    if any(phrase in lower for phrase in ["i could not find", "no relevant", "insufficient", "not enough information"]):
        return "low"
    if any(phrase in lower for phrase in ["[inference]", "likely", "probably", "might be"]):
        return "medium"
    return "high"


def _detect_inference(answer_text: str) -> bool:
    return "[inference]" in answer_text.lower() or "[infer" in answer_text.lower()


def _detect_intent(query: str) -> str:
    """Simple keyword-based intent detection."""
    lower = query.lower()
    if any(kw in lower for kw in ["explain", "how does", "what does", "what is"]):
        return "explanation"
    if any(kw in lower for kw in ["error", "bug", "500", "fail", "crash", "exception", "debug"]):
        return "debugging"
    if any(kw in lower for kw in ["architecture", "system design", "overview", "structure"]):
        return "architecture"
    if any(kw in lower for kw in ["database", "schema", "collection", "model", "field"]):
        return "database"
    if any(kw in lower for kw in ["api", "endpoint", "route", "http", "post", "get", "request"]):
        return "api"
    return "knowledge"


class AnswerService:
    def __init__(self):
        self.settings = get_settings()
        self.searcher = get_hybrid_searcher()
        self.llm = get_llm()

    def answer(
        self,
        query: str,
        session_id: str,
        history: list[dict] | None = None,
        mode: str = "chat",
    ) -> ChatResponse:
        """
        Main RAG Q&A:
        1. Detect intent to choose source_type filters
        2. Hybrid search (semantic + BM25)
        3. Rerank
        4. Build context
        5. Call Gemini
        6. Return structured response
        """
        intent = _detect_intent(query)
        logger.info(f"Query intent: {intent} | Query: {query[:60]}")

        # Choose source type filters based on intent
        source_filters = None
        if intent == "debugging":
            source_filters = ["code", "github_issue", "commit", "documentation"]
        elif intent == "database":
            source_filters = ["code", "documentation"]
        elif intent == "api":
            source_filters = ["code", "documentation"]

        # Step 1: Hybrid retrieval
        docs = self.searcher.search(
            query,
            top_k=self.settings.retrieval_top_k,
            source_types=source_filters,
        )

        # Step 2: Rerank
        docs = rerank(query, docs, top_k=self.settings.rerank_top_k)

        # Step 3: Build context
        context = build_context(docs)
        sources = documents_to_source_chunks(docs)

        # Step 4: Build history string
        history_str = ""
        if history:
            history_str = "\n".join(
                f"{m['role'].upper()}: {m['content']}" for m in history[-6:]
            )

        # Step 5: Select prompt based on mode
        if mode == "explain":
            prompt = code_prompt
        else:
            prompt = answer_prompt

        # Step 6: Call LLM
        try:
            chain = prompt | self.llm
            response = chain.invoke({
                "context": context,
                "history": history_str or "No previous conversation.",
                "question": query,
            })
            answer_text = response.content
            # Remove any stray confidence lines if generated by the LLM
            answer_text = re.sub(
                r'(?im)^(?:\*\*|\*|#+\s*)?confidence(?:\s*level)?:\s*(?:high|medium|low)(?:\*\*|\*)?\s*$',
                '',
                answer_text
            )
            answer_text = re.sub(
                r'(?im)^(?:\*\*|\*|#+\s*)?(?:high|medium|low)\s+confidence(?:\*\*|\*)?\s*$',
                '',
                answer_text
            )
            answer_text = re.sub(r'\n{3,}', '\n\n', answer_text).strip()
        except Exception as e:
            logger.error(f"LLM call failed: {e}")
            answer_text = (
                "I encountered an error while generating the response. "
                "Please check that your GEMINI_API_KEY is valid and try again."
            )

        return ChatResponse(
            session_id=session_id,
            answer=answer_text,
            confidence=_detect_confidence(answer_text),
            sources=sources,
            inference=_detect_inference(answer_text),
            mode=mode,
        )
